/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.netology.pyas;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CalculatorTest {

    private final static double EPS = 1e-2;

    @Test
    void testMonthlyPayment() {
        Calculator calculator = new Calculator(100_000, 7, 3*12);
        double expected = 3_087.71;
        double actual = calculator.monthlyPayment();
        assertEquals(expected, actual, EPS);
    }

    @Test
    void testOverpaymentSize() {
        Calculator calculator = new Calculator(100_000, 7, 3*12);
        double expected = 11_157.54;
        double actual = calculator.overpaymentSize();
        assertEquals(expected, actual, EPS);
    }

    @Test
    void testRefundableAmount() {
        Calculator calculator = new Calculator(100_000, 7, 3*12);
        double expected = 111_157.54;
        double actual = calculator.refundableAmount();
        assertEquals(expected, actual, EPS);
    }
}
